apiVersion: v1
kind: Service
metadata:
  name: dns-service-tcp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: "dns-svc-ip"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    app: dns
---
apiVersion: v1
kind: Service
metadata:
  name: dns-svc-udp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: "dns-svc-ip"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  ports:
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: dns    