apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: admin
rules:
- apiGroups: ["*"] # "" означает apiGroup под именем core или legacy
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devadmin
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jane
  apiGroup: ""
roleRef:
  kind: Role
  name: admin
  apiGroup: ""

