apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: netperfs.app.example.com
spec:
  group: app.example.com
  names:
    kind: Netperf
    listKind: NetperfList
    plural: netperfs
    singular: netperf
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description:
          properties:
            apiVersion:
              description:
              type: string
            kind:
              description:
              type: string
            metadata:
              type: object
            spec:
              description:
              properties:
                serverNode:
                  type: string
                clientNode:
                  type: string
              required:
                - serverNode
                - clientNode
              type: object
            status:
              description:
              properties:
                status:
                  type: string
                serverPod:
                  type: string
                clientPod:
                  type: string
                speedBitsPerSec:
                  type: number
              type: object
          type: object