apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: prometheus
  name: pod-reader
rules:
- apiGroups: [""] # "" означает apiGroup под именем core или legacy
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-role
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io