apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mon
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  selector:
    matchLabels:
      app: nginx-mon
  template:
    metadata:
      labels:
        app: nginx-mon
    spec:
      containers:
      - name: nginx-mon
        image:  akha/otus-nginx-mon:latest
        livenessProbe:
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
#        volumeMounts:
#        - name: app
#          mountPath: /app
#      volumes:
#      - name: app
#        emptyDir: {}
