apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework # имя CRD должно иметь формат plural.group
spec:
  scope: Namespaced     # Данный CRD будер работать в рамках namespace
  group: otus.homework  # Группа, отражается в поле apiVersion CR
  versions:             # Список версий
    - name: v1
      served: true      # Будет ли обслуживаться API-сервером данная версия
      storage: true     # Фиксирует  версию описания, которая будет сохраняться в etcd
      schema: #обязательный раздел в v1
        openAPIV3Schema:
          description: Mysql Scheme
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of Mysql
              properties: # свойства спецификации
                image:
                  description: image for MySQL
                  type: string
                database:
                  description: MySQL db name
                  type: string
                password:
                  description: MySQL admin passwd
                  type: string
                storage_size:
                  description: MySQL storage size
                  type: string
              required:
              - image
              - database
              - password
              - storage_size
              type: object
            status:
              description: MySQLStatus defines the observed state of MySQL
              type: object
          type: object
  names:                # различные форматы имени объекта CR
    kind: MySQL         # kind CR
    plural: mysqls      
    singular: mysql
    shortNames:
      - ms