tolerations:
  - operator: "Exists"

config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On        
    [INPUT]
        Name tail
        Tag nginx.*
        Path /var/log/containers/ingress-nginx-controller*.log
        multiline.parser k8s-nginx-ingress
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix kube
        Retry_Limit False
        tls On
        tls.verify Off
        http_user elastic
        http_passwd t2t02q1jlSWw5f1b
        Suppress_Type_Name On
    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        tls On
        tls.verify Off
        http_user elastic
        http_passwd t2t02q1jlSWw5f1b
        Suppress_Type_Name On
    [OUTPUT]
        Name es
        Match nginx.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix nginx
        Retry_Limit False
        tls On
        tls.verify Off
        http_user elastic
        http_passwd t2t02q1jlSWw5f1b
        Suppress_Type_Name On
  customParsers: |
    [PARSER]
        Name k8s-nginx-ingress
        Format regex
        Regex ^(?<host>[^ ]*) - \[(?<real_ip>[^ ]*)\] - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<last>[^$]*)
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log
        Decode_Field_As   escaped    stream
#    [INPUT]
#        Name systemd
#        Tag host.*
#        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
#        Read_From_Tail On

